let header = document.getElementById('add-post-title-id');
console.log(header);
console.log(header.id);
console.log(header.className);
console.log(header.classList);
header.style.backgroundColor = "red";
header.style.color = "white";
header.style.padding = "15px";
//header.style.display = 'none';
header.textContent = "Hi Ismile!!";
header.innerText = "Hi Shuvo!!";
header.innerHTML = '<span style = "color:black">Hi Mikhel!! </span>';
